#!/usr/bin/env bash
# ============================================================
# ForgeOS Module 02 - Network
# Configures networking for a stable NAS.
#
# Does:
#   - Static IP setup (optional, preserves DHCP if preferred)
#   - DNS configuration (local + upstream)
#   - Optional NIC bonding (for redundancy / throughput)
#   - mDNS / Avahi for .local discovery
#   - Wake-on-LAN
#   - Predictable NIC naming verification
# ============================================================
set -euo pipefail
source "$(dirname "$0")/../lib/common.sh"
source "$FORGENAS_CONFIG"

# ============================================================
# AVAHI / MDNS
# Makes the NAS discoverable at hostname.local on the LAN.
# Required by ForgeFileDB, Samba with mDNS, iOS Time Machine.
# ============================================================
configure_mdns() {
    step "Configuring mDNS / Avahi"

    apt_install avahi-daemon avahi-utils libnss-mdns

    source "$FORGENAS_CONFIG"
    local hostname="${HOSTNAME:-forgeos}"
    local domain="${DOMAIN:-nas.local}"

    cat > /etc/avahi/avahi-daemon.conf << AVAHI
[server]
host-name=${hostname}
domain-name=local
use-ipv4=yes
use-ipv6=yes
allow-interfaces=${NIC_PRIMARY:-eth0}
enable-dbus=yes
deny-interfaces=docker0,br-,incus,lxdbr0,virbr

[wide-area]
enable-wide-area=yes

[publish]
publish-addresses=yes
publish-hinfo=yes
publish-workstation=yes
publish-domain=yes
AVAHI

    # NSSwitch — resolve .local names via mDNS
    if ! grep -q 'mdns4_minimal' /etc/nsswitch.conf; then
        sed -i 's/^hosts:.*/hosts:          files mdns4_minimal [NOTFOUND=return] dns/' /etc/nsswitch.conf
    fi

    enable_service avahi-daemon
    info "mDNS: ${hostname}.local  (Avahi)"
}

# ============================================================
# STATIC IP (optional)
# NAS devices should have a predictable IP.
# If STATIC_IP is set in forgeos.conf, configure it.
# Otherwise, leave DHCP and remind user.
# ============================================================
configure_static_ip() {
    source "$FORGENAS_CONFIG"

    [[ "${STATIC_IP:-}" == "" ]] && {
        info "Static IP: not configured (using DHCP)"
        info "  To set static IP: add STATIC_IP=x.x.x.x to /etc/forgeos/forgeos.conf"
        info "  and re-run module 02, or configure via your router's DHCP reservation."
        return 0
    }

    step "Configuring static IP: ${STATIC_IP}"

    local nic="${NIC_PRIMARY:-eth0}"
    local gw="${STATIC_GW:-$(ip route | awk '/^default/{print $3}' | head -1)}"
    local dns="${STATIC_DNS:-1.1.1.1,8.8.8.8}"
    local prefix="${STATIC_PREFIX:-24}"

    # Detect netplan vs ifupdown
    if command -v netplan &>/dev/null && [[ -d /etc/netplan ]]; then
        _configure_netplan "$nic" "$STATIC_IP" "$prefix" "$gw" "$dns"
    else
        _configure_ifupdown "$nic" "$STATIC_IP" "$prefix" "$gw" "$dns"
    fi

    forgenas_set "NIC_CONFIGURED_IP" "$STATIC_IP"
    info "Static IP configured: ${STATIC_IP}/${prefix} gw ${gw}"
}

_configure_netplan() {
    local nic="$1" ip="$2" prefix="$3" gw="$4" dns="$5"

    # Backup existing configs
    mkdir -p /etc/netplan/backups
    cp /etc/netplan/*.yaml /etc/netplan/backups/ 2>/dev/null || true
    # Disable auto-configs that might conflict
    for f in /etc/netplan/00-*.yaml /etc/netplan/50-*.yaml; do
        [[ -f "$f" ]] && mv "$f" "${f}.disabled" 2>/dev/null || true
    done

    local dns_list; dns_list=$(echo "$dns" | tr ',' ' ' | awk '{for(i=1;i<=NF;i++) printf "          - "$i"\n"}')

    cat > /etc/netplan/90-forgeos.yaml << NETPLAN
# ForgeOS network configuration
# Generated by ForgeOS installer

network:
  version: 2
  renderer: networkd
  ethernets:
    ${nic}:
      dhcp4: no
      dhcp6: no
      addresses:
        - ${ip}/${prefix}
      routes:
        - to: default
          via: ${gw}
      nameservers:
        addresses:
${dns_list}
      mtu: 9000
      optional: true
NETPLAN

    chmod 600 /etc/netplan/90-forgeos.yaml
    netplan generate >> "$FORGENAS_LOG" 2>&1 || warn "netplan generate had warnings"
    netplan apply >> "$FORGENAS_LOG" 2>&1 || warn "netplan apply — check manually"
}

_configure_ifupdown() {
    local nic="$1" ip="$2" prefix="$3" gw="$4" dns="$5"

    cat >> /etc/network/interfaces << IFACES

# ForgeOS static IP
auto ${nic}
iface ${nic} inet static
    address ${ip}/${prefix}
    gateway ${gw}
    dns-nameservers ${dns//,/ }
    mtu 9000
IFACES

    ifdown "$nic" 2>/dev/null || true
    ifup "$nic" >> "$FORGENAS_LOG" 2>&1 || warn "Interface reconfiguration — check manually"
}

# ============================================================
# MTU / JUMBO FRAMES (optional, for 10GbE LANs)
# Only enable if switch also supports jumbo frames.
# Controlled by NIC_JUMBO_FRAMES=yes in forgeos.conf
# ============================================================
configure_jumbo_frames() {
    source "$FORGENAS_CONFIG"
    [[ "${NIC_JUMBO_FRAMES:-no}" != "yes" ]] && return 0

    step "Configuring jumbo frames (MTU 9000)"
    local nic="${NIC_PRIMARY:-eth0}"
    ip link set "$nic" mtu 9000 2>/dev/null || warn "Could not set MTU 9000"
    info "Jumbo frames (MTU 9000) enabled on $nic"
}

# ============================================================
# DNS RESOLVER
# Use systemd-resolved with local caching.
# Upstream: Cloudflare (privacy) + Google (fallback)
# ============================================================
configure_dns() {
    step "Configuring DNS resolver"

    apt_install_optional systemd-resolved

    mkdir -p /etc/systemd/resolved.conf.d
    cat > /etc/systemd/resolved.conf.d/forgeos.conf << 'DNS'
[Resolve]
DNS=1.1.1.1 8.8.8.8 2606:4700:4700::1111
FallbackDNS=9.9.9.9 149.112.112.112
DNSOverTLS=opportunistic
DNSSEC=allow-downgrade
Cache=yes
DNS

    systemctl restart systemd-resolved 2>/dev/null || true
    # Point /etc/resolv.conf to resolved stub
    ln -sf /run/systemd/resolve/stub-resolv.conf /etc/resolv.conf 2>/dev/null || true

    info "DNS: Cloudflare+Google via systemd-resolved (DoT when available)"
}

# ============================================================
# NIC BONDING (optional)
# Enabled when NIC_BOND=yes and at least 2 NICs available
# Modes: active-backup (failover), 802.3ad (LACP, needs switch)
# ============================================================
configure_bonding() {
    source "$FORGENAS_CONFIG"
    [[ "${NIC_BOND:-no}" != "yes" ]] && return 0
    [[ "${NIC_COUNT:-1}" -lt 2 ]] && { warn "Bonding requires 2+ NICs — skipping"; return 0; }

    step "Configuring NIC bonding (${NIC_BOND_MODE:-active-backup})"

    apt_install ifenslave

    local mode="${NIC_BOND_MODE:-active-backup}"
    local bond_ip="${NIC_IP:-}"

    if command -v netplan &>/dev/null; then
        # Detect available NICs (excluding primary which may be active)
        local nics=()
        while IFS= read -r nic; do
            [[ "$nic" =~ ^(lo|docker|br-|veth|incus|lxd|virbr) ]] && continue
            nics+=("$nic")
        done < <(ls /sys/class/net/)

        [[ ${#nics[@]} -lt 2 ]] && { warn "Not enough physical NICs for bonding"; return 0; }

        local nic_entries=""
        for nic in "${nics[@]:0:2}"; do
            nic_entries+="    ${nic}: {}\n"
        done

        cat > /etc/netplan/91-forgeos-bond.yaml << BOND
network:
  version: 2
  bonds:
    bond0:
      interfaces: [${nics[0]}, ${nics[1]}]
      addresses: [${bond_ip}/24]
      parameters:
        mode: ${mode}
        mii-monitor-interval: 100
        lacp-rate: slow
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]
  ethernets:
$(echo -e "$nic_entries")
BOND
        netplan apply >> "$FORGENAS_LOG" 2>&1 || warn "Bond netplan apply — check manually"
        forgenas_set "NIC_PRIMARY" "bond0"
    fi

    info "NIC bonding: bond0 (${mode}) using ${nics[0]} + ${nics[1]}"
}

# ============================================================
# WAKE-ON-LAN
# ============================================================
configure_wol() {
    source "$FORGENAS_CONFIG"
    local nic="${NIC_PRIMARY:-eth0}"

    apt_install ethtool

    # Enable WoL on NIC
    ethtool -s "$nic" wol g 2>/dev/null || true

    # Persist via systemd service
    cat > /etc/systemd/system/forgeos-wol.service << WOL
[Unit]
Description=ForgeOS Wake-on-LAN
After=network.target

[Service]
Type=oneshot
ExecStart=/sbin/ethtool -s ${nic} wol g
RemainAfterExit=yes

[Install]
WantedBy=multi-user.target
WOL
    systemctl enable forgeos-wol 2>/dev/null || true
    info "Wake-on-LAN: enabled on $nic"
}

# ============================================================
# MAIN
# ============================================================
configure_mdns
configure_static_ip
configure_jumbo_frames
configure_dns
configure_bonding
configure_wol

forgenas_set "MODULE_NETWORK_DONE" "yes"
info "Network module complete"
info "  Hostname: $(hostname).local (mDNS)"
info "  IP:       $(ip -4 addr show scope global | awk '/inet /{print $2}' | head -1)"
