#!/usr/bin/env bash
# ============================================================
# ForgeOS Module 12 - Reverse Proxy (nginx)
#
# WHY NGINX OVER CADDY:
#   - Caddy WebDAV requires custom xcaddy build (fragile)
#   - Caddy admin API hot-reload has known race conditions
#     under concurrent requests (upstream issues #4817, #5249)
#   - nginx has 15+ years of production hardening
#   - nginx + certbot is the most battle-tested TLS stack
#     on Linux, period
#   - nginx config is auditable by every sysadmin alive
#   - nginx-extras ships with Lua, more auth modules, headers
#
# Stack:
#   nginx (mainline) + certbot (Let's Encrypt) + acme.sh
#   ForgeOS manages nginx via Python config generator API
#   No manual nginx.conf editing required (GUI does it)
# ============================================================
source "$(dirname "$0")/../lib/common.sh"
source "$FORGENAS_CONFIG"

NGINX_CONF_DIR="/etc/nginx"
FORGEOS_VHOSTS="/etc/nginx/forgeos.d"
CERT_DIR="/etc/forgeos/certs"

# ============================================================
# INSTALL NGINX MAINLINE
# ============================================================
install_nginx() {
    step "Installing nginx (mainline)"

    # nginx official repo for mainline (not Ubuntu's older stable)
    local codename
    codename=$(lsb_release -cs)

    curl -fsSL https://nginx.org/keys/nginx_signing.key \
        | gpg --dearmor -o /usr/share/keyrings/nginx-archive-keyring.gpg 2>/dev/null

    cat > /etc/apt/sources.list.d/nginx.list << REPO
deb [signed-by=/usr/share/keyrings/nginx-archive-keyring.gpg] \
http://nginx.org/packages/mainline/ubuntu ${codename} nginx
REPO

    apt_install nginx nginx-extras

    # Disable default site
    rm -f /etc/nginx/conf.d/default.conf
    mkdir -p "$FORGEOS_VHOSTS" "$CERT_DIR"

    info "nginx $(nginx -v 2>&1 | grep -oP '[\d.]+') installed"
}

# ============================================================
# CERTBOT (Let's Encrypt)
# ============================================================
install_certbot() {
    step "Installing certbot (Let's Encrypt)"

    apt_install certbot python3-certbot-nginx

    # Also install acme.sh as fallback / Cloudflare DNS challenge support
    if [[ ! -f ~/.acme.sh/acme.sh ]]; then
        curl -s https://get.acme.sh 2>/dev/null | bash -s email="${ACME_EMAIL:-admin@example.com}" \
            >> "$FORGENAS_LOG" 2>&1 \
            || warn "acme.sh install failed (certbot still available)"
    fi

    # Auto-renew hook: reload nginx after renewal
    cat > /etc/letsencrypt/renewal-hooks/deploy/forgeos-reload.sh << 'HOOK'
#!/bin/bash
nginx -t && systemctl reload nginx
# Sync certs to services that need them directly
CERT_DIR="/etc/forgeos/certs"
for domain_dir in /etc/letsencrypt/live/*/; do
    domain=$(basename "$domain_dir")
    mkdir -p "${CERT_DIR}/${domain}"
    cp "${domain_dir}fullchain.pem" "${CERT_DIR}/${domain}/"
    cp "${domain_dir}privkey.pem"   "${CERT_DIR}/${domain}/"
    chmod 640 "${CERT_DIR}/${domain}/privkey.pem"
done
# Signal mail services to reload (Postfix, Dovecot)
systemctl is-active postfix  &>/dev/null && systemctl reload postfix
systemctl is-active dovecot  &>/dev/null && systemctl reload dovecot
HOOK
    chmod +x /etc/letsencrypt/renewal-hooks/deploy/forgeos-reload.sh

    info "certbot installed with auto-reload hooks"
}

# ============================================================
# NGINX BASE CONFIGURATION
# Production-hardened, security-first
# ============================================================
configure_nginx_base() {
    step "Configuring nginx base"

    # Detect CPU count for worker_processes
    local cpus; cpus=$(nproc)

    cat > "$NGINX_CONF_DIR/nginx.conf" << NGINX
# ForgeOS nginx main configuration
# Generated by ForgeOS installer — edit via Web UI > Proxy

user  nginx;
worker_processes ${cpus};
worker_rlimit_nofile 65535;
error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections 4096;
    use epoll;
    multi_accept on;
}

http {
    # ── MIME types ──────────────────────────────
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # ── Logging format ──────────────────────────
    log_format  main  '\$remote_addr [\$time_local] "\$request" '
                      '\$status \$body_bytes_sent '
                      '"\$http_referer" "\$http_user_agent" '
                      'rt=\$request_time';
    access_log  /var/log/nginx/access.log  main buffer=64k flush=5s;

    # ── Performance ─────────────────────────────
    sendfile           on;
    tcp_nopush         on;
    tcp_nodelay        on;
    keepalive_timeout  65;
    keepalive_requests 1000;
    reset_timedout_connection on;
    client_body_timeout   30;
    client_header_timeout 30;
    send_timeout          30;

    # ── Compression ─────────────────────────────
    gzip             on;
    gzip_vary        on;
    gzip_proxied     any;
    gzip_comp_level  4;
    gzip_min_length  1000;
    gzip_types text/plain text/css application/json application/javascript
               text/xml application/xml image/svg+xml;

    # ── File upload size ────────────────────────
    client_max_body_size 10g;
    client_body_buffer_size 128k;

    # ── Security headers (global) ───────────────
    server_tokens off;                       # Hide nginx version
    add_header X-Frame-Options SAMEORIGIN always;
    add_header X-Content-Type-Options nosniff always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy  "strict-origin-when-cross-origin" always;
    # HSTS set per-vhost after TLS confirmed

    # ── TLS session cache ───────────────────────
    ssl_session_cache   shared:SSL:50m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    # ── Modern TLS only ─────────────────────────
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256;
    ssl_prefer_server_ciphers off;
    ssl_dhparam         /etc/nginx/dhparam.pem;

    # ── OCSP stapling ───────────────────────────
    ssl_stapling        on;
    ssl_stapling_verify on;
    resolver            1.1.1.1 8.8.8.8 valid=300s;
    resolver_timeout    5s;

    # ── Rate limiting zones ─────────────────────
    limit_req_zone \$binary_remote_addr zone=forgeos_ui:10m   rate=20r/s;
    limit_req_zone \$binary_remote_addr zone=forgeos_auth:10m rate=5r/m;
    limit_req_zone \$binary_remote_addr zone=forgeos_api:10m  rate=60r/s;
    limit_conn_zone \$binary_remote_addr zone=forgeos_conn:10m;

    # ── Proxy settings shared by all upstreams ──
    proxy_http_version      1.1;
    proxy_set_header Host              \$host;
    proxy_set_header X-Real-IP         \$remote_addr;
    proxy_set_header X-Forwarded-For   \$proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto \$scheme;
    proxy_set_header Upgrade           \$http_upgrade;
    proxy_set_header Connection        "upgrade";
    proxy_read_timeout  600s;
    proxy_send_timeout  600s;
    proxy_buffering     off;          # Needed for streaming/WebSocket

    # ── WebSocket map ───────────────────────────
    map \$http_upgrade \$connection_upgrade {
        default upgrade;
        ''      close;
    }

    # ── ForgeOS vhosts ──────────────────────────
    include ${FORGEOS_VHOSTS}/*.conf;
}
NGINX

    # Generate strong DH params (2048-bit, quick; 4096 takes too long for install)
    if [[ ! -f /etc/nginx/dhparam.pem ]]; then
        info "Generating DH params (this takes ~30s)..."
        openssl dhparam -out /etc/nginx/dhparam.pem 2048 >> "$FORGENAS_LOG" 2>&1
    fi

    info "nginx base configuration complete"
}

# ============================================================
# VHOST GENERATOR FUNCTION
# Called during install + by Web UI backend to add services
# ============================================================
nginx_add_vhost() {
    # Usage: nginx_add_vhost <name> <domain> <upstream_port> [options]
    local name="$1" domain="$2" port="$3"
    local tls="${4:-acme}"       # acme | selfsigned | none
    local auth="${5:-none}"      # none | basic | oidc
    local ws="${6:-no}"          # WebSocket support

    local conf="${FORGEOS_VHOSTS}/${name}.conf"
    local upstream="http://127.0.0.1:${port}"

    # Get cert paths
    local cert_path="/etc/letsencrypt/live/${domain}/fullchain.pem"
    local key_path="/etc/letsencrypt/live/${domain}/privkey.pem"

    # Fall back to self-signed if ACME cert not yet issued
    if [[ ! -f "$cert_path" ]]; then
        cert_path="/etc/nginx/selfsigned/${domain}.crt"
        key_path="/etc/nginx/selfsigned/${domain}.key"
        mkdir -p /etc/nginx/selfsigned
        if [[ ! -f "$cert_path" ]]; then
            openssl req -x509 -nodes -newkey rsa:2048 \
                -keyout "$key_path" -out "$cert_path" \
                -days 365 -subj "/CN=${domain}" >> "$FORGENAS_LOG" 2>&1
        fi
    fi

    cat > "$conf" << VHOST
# ForgeOS vhost: ${name} → ${upstream}
# Managed by ForgeOS — modify via Web UI > Proxy > Sites

upstream forgeos_${name} {
    server 127.0.0.1:${port};
    keepalive 32;
}

# HTTP → HTTPS redirect
server {
    listen 80;
    listen [::]:80;
    server_name ${domain};
    return 301 https://\$host\$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;
    http2 on;
    server_name ${domain};

    ssl_certificate     ${cert_path};
    ssl_certificate_key ${key_path};

    # HSTS (6 months)
    add_header Strict-Transport-Security "max-age=15768000; includeSubDomains" always;

    # Content Security Policy
    add_header Content-Security-Policy "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: blob:; font-src 'self' data:; connect-src 'self' wss://\$host;" always;

    # Rate limiting
    limit_conn forgeos_conn 100;
    limit_req  zone=forgeos_api burst=20 nodelay;

    # Logging
    access_log /var/log/nginx/${name}-access.log main;
    error_log  /var/log/nginx/${name}-error.log warn;

    location / {
        proxy_pass http://forgeos_${name};
        $([ "$ws" == "yes" ] && echo "proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection \$connection_upgrade;" || true)
    }

    # Health check (internal only)
    location /_forgeos_health {
        allow 127.0.0.1;
        deny all;
        return 200 "ok";
    }
}
VHOST

    info "vhost created: $domain → 127.0.0.1:$port"
}

# ============================================================
# GENERATE ALL FORGEOS SERVICE VHOSTS
# ============================================================
generate_vhosts() {
    step "Generating ForgeOS service vhosts"

    source "$FORGENAS_CONFIG"
    local d="${DOMAIN:-nas.local}"
    local email="${ACME_EMAIL:-admin@${d}}"

    # Attempt ACME cert for wildcard or individual subdomains
    if [[ "$d" != "nas.local" && "$d" != "localhost" ]]; then
        info "Requesting Let's Encrypt certs..."
        certbot certonly --nginx --non-interactive --agree-tos \
            --email "$email" -d "$d" \
            $(for sub in mail photos office grafana auth push s3 s3api files dav vpn; do
                echo "-d ${sub}.${d} "
            done) >> "$FORGENAS_LOG" 2>&1 \
            || info "Cert issuance deferred — run: certbot --nginx -d ${d}"
    fi

    # Main Web UI
    nginx_add_vhost "forgeos-ui"   "${d}"               5080 acme none yes

    # Services (conditionally based on installed modules)
    local has_mail; has_mail=$(forgenas_get FEATURE_14-mail 2>/dev/null)
    local has_immich; has_immich=$(forgenas_get FEATURE_IMMICH 2>/dev/null)

    nginx_add_vhost "grafana"      "grafana.${d}"       3000 acme none no
    nginx_add_vhost "gotify"       "push.${d}"          8070 acme none yes
    nginx_add_vhost "minio-ui"     "s3.${d}"            9001 acme none no
    nginx_add_vhost "minio-api"    "s3api.${d}"         9000 acme none no
    nginx_add_vhost "filebrowser"  "files.${d}"         8085 acme none yes
    nginx_add_vhost "authentik"    "auth.${d}"          9000 acme none yes

    [[ "$has_mail" == "yes" ]] && nginx_add_vhost "sogo" "mail.${d}" 20000 acme none yes
    [[ "$has_immich" == "yes" ]] && nginx_add_vhost "immich" "photos.${d}" 2283 acme none yes

    # WebDAV (full read/write via nginx WebDAV module)
    cat > "${FORGEOS_VHOSTS}/webdav.conf" << DAVCONF
# ForgeOS WebDAV — nginx native WebDAV (no plugin needed)
server {
    listen 443 ssl;
    http2 on;
    server_name dav.${d};
    ssl_certificate     /etc/letsencrypt/live/${d}/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/${d}/privkey.pem;
    add_header Strict-Transport-Security "max-age=15768000" always;

    root /srv/nas;
    client_max_body_size 10g;
    client_body_temp_path /tmp/nginx-dav-upload;

    # nginx WebDAV module (ships with nginx-extras)
    dav_methods     PUT DELETE MKCOL COPY MOVE;
    dav_ext_methods PROPFIND OPTIONS;
    dav_access      user:rw group:r;
    create_full_put_path on;

    location / {
        auth_basic           "ForgeOS WebDAV";
        auth_basic_user_file /etc/nginx/webdav-htpasswd;
    }

    location ~ ^/public/ {
        auth_basic off;
        dav_access user:rw group:r all:r;
    }
}
DAVCONF

    # Create htpasswd placeholder
    touch /etc/nginx/webdav-htpasswd
    chmod 640 /etc/nginx/webdav-htpasswd

    # Test and reload
    nginx -t >> "$FORGENAS_LOG" 2>&1 || die "nginx config test failed — check $FORGENAS_LOG"
    enable_service nginx
    info "All vhosts generated and nginx started"
}

# ============================================================
# NGINX MANAGEMENT API
# Used by Web UI backend to add/update/remove vhosts without restart
# ============================================================
create_nginx_api() {
    step "Creating nginx management API"

    cat > /usr/local/bin/forgeos-nginx << 'NGXAPI'
#!/usr/bin/env bash
# ForgeOS nginx management tool
# Called by Web UI backend via subprocess
set -euo pipefail
source /etc/forgeos/forgeos.conf

CMD="${1:-help}"
shift || true

reload_nginx() {
    nginx -t || { echo "Config test failed"; exit 1; }
    systemctl reload nginx
    echo "nginx reloaded"
}

case "$CMD" in
    add-vhost)
        # Args: <name> <domain> <port> [tls] [auth] [ws]
        source /opt/forgeos/install/modules/12-reverse-proxy.sh 2>/dev/null || true
        nginx_add_vhost "$@"
        reload_nginx
        ;;
    remove-vhost)
        rm -f "/etc/nginx/forgeos.d/${1}.conf"
        reload_nginx
        ;;
    add-webdav-user)
        # Args: <username> <password>
        htpasswd -b /etc/nginx/webdav-htpasswd "$1" "$2"
        echo "WebDAV user $1 added"
        ;;
    remove-webdav-user)
        htpasswd -D /etc/nginx/webdav-htpasswd "$1"
        echo "WebDAV user $1 removed"
        ;;
    request-cert)
        # Args: <domain> [email]
        local domain="$1" email="${2:-${ACME_EMAIL:-admin@${DOMAIN}}}"
        certbot certonly --nginx --non-interactive --agree-tos \
            --email "$email" -d "$domain"
        reload_nginx
        ;;
    list)
        echo "=== ForgeOS nginx vhosts ==="
        for f in /etc/nginx/forgeos.d/*.conf; do
            [[ -f "$f" ]] || continue
            echo "  $(basename "$f" .conf)"
        done
        echo ""
        echo "=== Active certs ==="
        certbot certificates 2>/dev/null || true
        ;;
    test)
        nginx -t
        ;;
    reload)
        reload_nginx
        ;;
    status)
        systemctl status nginx --no-pager -l | head -20
        ;;
    help|*)
        echo "ForgeOS nginx manager"
        echo "  add-vhost <name> <domain> <port>"
        echo "  remove-vhost <name>"
        echo "  add-webdav-user <user> <pass>"
        echo "  request-cert <domain> [email]"
        echo "  list | test | reload | status"
        ;;
esac
NGXAPI
    chmod +x /usr/local/bin/forgeos-nginx
    info "forgeos-nginx management tool installed"
}

# ============================================================
# MAIN
# ============================================================
install_nginx
install_certbot
configure_nginx_base
generate_vhosts
create_nginx_api

forgenas_set "PROXY" "nginx"

info "Reverse proxy module complete (nginx)"
info "  Add vhosts:   forgeos-nginx add-vhost <name> <domain> <port>"
info "  List vhosts:  forgeos-nginx list"
info "  Reload:       forgeos-nginx reload"
